### ISSUE TITLE
T: 07/4 Maquetación Componentes Home

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebLandingEcommerce#1]
**Overview**
Maquetación Componentes Home

**Issues**
- [x] Banner top #70
- [x] Carrusel para banners principales #72
- [x] Carrusel de categorías #73 
- [x] Carrusel de liquidación #74
- [x] Banners de promoción #75
- [x] Sección visa responsive #76 
- [x] #78 Sección Productos
- [x] Crear Componente Chat 
- [x] Agregar componente informacion
