### ISSUE TITLE
T: 07/4 Detalle de categorías TE - 25.5 H

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebLandingEcommerce#10]
**Overview**
Detalle de categorías

**Issues**
- [x] Menú de sub categorías  
- [x] Filtros de categorías #91 
- [x] Listado paginado de productos por categoría #130  
- [x]  Integrar Servicio filtrado por SubCategoria #187 2h
- [x] Verificar componente submenu Categorias responsive #200  3h
- [x] Mostrar slider componente al seleccionar una categoria #201 3h
- [x] Crear BreadCrumbs categorias #202 3.5 h
- [x] Integrar Selects filtros por categoria #204 3.5h
- [x] Integrar Precio filtros por Categoria  #208 2 h
