### ISSUE TITLE
Semana 2 Diciembre - TE: 14.5

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#1007]
### Tarjeta de producto
- [x] 0.5 h Mostrar tipo de moneda en tarjeta de productos #1006

### Imágenes en detalle de producto
- [x] 1 h Filtrar imágenes en detalle de producto por variable `fromApp` #1011 
- [x] 1 h Cambiar orden de botones de características versión [móvil](https://app.zeplin.io/project/5ccb19f5fecb6468267cd951/dashboard?tag=A-MEJORAR) #1013
- [x] 2 h Agregar botones para cambiar imágenes en carrusel versión [móvil](https://app.zeplin.io/project/5ccb19f5fecb6468267cd951/dashboard?tag=A-MEJORAR)

### Pasarelas de pago
- [x] 3 h Notificaciones y validaciones de campos para mercadopago
- [x] 8 h Flujo YAPE
