### ISSUE TITLE
T:07/5 Integracion Home TE: 4.5

### ISSUE THREAD

**Issue by elenaJO** [apprunn/dp6WebLandingEcommerce#101]
**Overview**
Integracion Home

**Issues**

- [x] Agregar link Iniciar sesion y crear cuenta #103
- [x] Integrar categorias #105 
- [x] Integrar banner principal #104
- [x] Integrar fltros #205
~~- [ ] 1.5h - Integrar Liquidacion #132~~
~~- [ ] 1h - Integrar boletin #135~~
- [x] 1.5h - Integracion header al loguearse #108
- [x] 1.5h - Integrar Buscador #207
