### ISSUE TITLE
I[1](REV): Revisión actividad levantada en trello referente a Yape

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#1043]
**Topic**
N/A

**Description**
No se visualiza el medio de pago Yape y en la consola del navegador aparece un error

**Acceptance Test**
- [x] Ingresar al commercio: https://casanaturistahierbasana.netlify.app/
- [x] Iniciar sesión con: adavila@apprunn.com, 123456
- [x] Hacer el flujo del carrito de compras
- [x] Verificar que el servicio `public` tenga a **Yape** como medio de pago
- [x] Verificar se muestre el botón de Yape como opción de pago

**Implementation Notes**
_**Required.** Write "none" if you think that there are not implementation notes._

**Subtasks**
_**Required.** Write "N/A" if there are not subtasks._

**Planning Estimate**
0.5 h

**References**
https://trello.com/c/38qRqf9c/73-error-en-consola-al-cargar-los-medios-de-pago

**Latest Assets**
N/A

**Comment by JoseJuan81** [comment]
No se muestra el botón de pago porque ocurre un error en la siguiente función
<img width="401" alt="Captura de Pantalla 2021-01-15 a la(s) 9 49 40 a  m" src="https://user-images.githubusercontent.com/21971589/104741374-1d28a780-5717-11eb-8c37-218c0dcf1e8d.png">
debido  a que no fue considerado otro tipo de depósito y no es posible llamar al método `call()` de indefinido
