### ISSUE TITLE
T: 07/4 Detalle de producto - TE: 23.5 h

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebLandingEcommerce#11]
**Overview**
Detalle de producto

**Issues**
- [x] 3h - Pre visualizador de producto #119 
- [x] 1.5h - Datos del producto #120
- [x] 5.5h - Características de producto #121
- [x] 3.5h - Modal y mapa de disponibilidad de producto #123
- [x] 2.5h - Botones para agregar cantidad y agregar a carrito #124
- [x] 3.5h - Sección tabs información de producto #126
- [x] 2h - Carrusel productos relacionados #127
- [x] 1.5h - Seccion publicidad #129
