### ISSUE TITLE
I:[2.5](PRO) Reducir el tamaño del Bottom flotante  y almacenar el teléfono del cliente en los pagos

### ISSUE THREAD

**Issue by Ivan-dela-cruz** [apprunn/dp6WebLandingEcommerce#1142]
**Description**
Reducir el tamaño del Bottom flotante  y almacenar el teléfono del cliente en los pagos

**Acceptance Test**
Reducir el tamaño del Bottom flotante  y almacenar el teléfono del cliente en los pagos

**Implementation Notes**

- [x] Reducir el tamaño del bottom  flotante para el carrito 
- [x] Agregar evento para redirigir a la pagina de pago en el bootom flotante del carrito
- [x] Mostar el numero de telefono que fue usado al realizar la primera compra
- [x] Validar cantidades de stock negativo paar los productos
- [x] Validar existencia de lista de precios al por mayor
- [x] Corregir error en consola cuando se recarga la pagina del de resumen de la compra

**Subtasks**
N/A

**Planning Estimate**
N/A

**References**
N/A

**Latest Assets**
N/A
