### ISSUE TITLE
I:[2](PRO) Mejoras en el diseño del detalle y carrito de compras

### ISSUE THREAD

**Issue by Ivan-dela-cruz** [apprunn/dp6WebLandingEcommerce#1158]
**Description**
Mejoras en el diseño del detalle y carrito de compras

**Acceptance Test**
- [x] Enviar al detalle del producto cuando presiono en la foto del producto. 
- [x] Agregar link en la categoria y poner border line. 
- [x] Quitar palabra producto en el carrito. 
- [x] Mostrar unidad en el carrito. 
- [x] Reducir tamaños de letras en el detalle del producto.
- [x] Cambiar cantidades del carrito para unicamente el detalle 
- [x] Cambiar el precio del producto del modal por el valor del detalle comprado
- [x] Mostrar unidades y precio por unidades

**Implementation Notes**
none

**Subtasks**
N/A

**Planning Estimate**
2

**References**
N/A

**Latest Assets**
N/A
