### ISSUE TITLE
T: 07/4 Carrito de compra (Estructura básica)  - TE: 2 h

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebLandingEcommerce#12]
**Overview**
Carrito de compra

**Issues**
- [x] #84 Estructura básica de carrito de compras
- [x] #88 Flujo básico para generar pedido e integrar pasarela visa
- [x] #99 Item de producto agregado
- [x] #115 Maquetar componente que muestra resumen de orden en carrito de compras
- [x] #142 2 h - Integración de componentes creados para crear primera pantalla del carrito de compras
