### ISSUE TITLE
T: 08/06 - ¿Cómo quiere recibir su producto? - TE: 10 h

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#122]
**Overview**
Sección ¿Cómo quiere recibir su producto? en flujo del carrito de compras

**Issues**
- [x] 1h - #146 Crear botones de selección de tipo de recepción de producto
- [x] 5 h - #152 Crear componente de dirección que muestra modal con mapa
- [x] 1.5 h - #150 Crear formulario de dirección nueva
- [x] 1.5 h - #148 Crear formulario de responsable de recibir productos de la orden
- [x] 2 h - #152 Insertar esta sección en la segunda pantalla del carrito de compras
