### ISSUE TITLE
T: 08/06 Sección Facturación en carrito de compras - TE: 5 h

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#125]
**Overview**
Creación de sección de ***Facturación*** en segunda pantalla del carrito de compras

**Issues**
- [x] 1 h - #162 Crear formulario de facturación
- [x] 1.5 h - #163  Crear componente ***Switch*** para sección de facturación
- [x] 1 h - #164 Crear sección de facturación con los componente anteriormente creados
- [x] 1.5 h - #165 Insertar sección de ***facturación*** en segunda pantalla del carrito de compras
