### ISSUE TITLE
T: 07/4 Centro de ayuda TE - 11h

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebLandingEcommerce#13]
**Overview**
Centro de ayuda

**Issues**
- [x] Crear Estructura para centro de ayuda #134 
- [x] Menú centro de ayuda #138 
- [x] Garantía #139 
- [x] Mostrar Listado de Centro de Ayuda (Responsive) #156
