### ISSUE TITLE
T: 08/06 - Pantalla de pago - TE: 12 h

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#131]
**Overview**
Pantalla de pago de orden en flujo del carrito de compras

**Issues**
- [x] 2 h - #193 Crear componente de datos generales en pantalla de pago
- [x] 1 h - #191 Crear componente de productos.
- [x] 4 h - #196 Crear componente de tipos de pago.
- [x] 2 h - #196 Agrupar componentes en tercera pantalla del carrito de compras 
- [x] 3 h - #196 Integrar servicio en tercera pantalla del carrito de compras
