### ISSUE TITLE
T: 08/06 Integrar servicios en perfil de usuario - TE: 8 h

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#133]
**Overview**
Integrar servicios web para las pantallas ya maquetadas (datos de usuario, ordenes y detalle de ordenes)

**Issues**
- [x] 2.5 h - Integrar servicio web para mostrar y editar datos del usuario en perfil de usuario
- [x] 1 h - #179 Integrar servicio web para mostrar ordenes generadas
- [x] 1 h - #181 Integrar servicio web para mostrar detalle de una determinada orden.
- [x] 3 h - #186 Integrar servicio web para mostrar, comprar y eliminar productos favoritos
