### ISSUE TITLE
T[6]: Correcciones para las tiendas online

### ISSUE THREAD

**Issue by christopher-qc** [apprunn/dp6WebLandingEcommerce#1383]
**Topic**
- [x] Lo se visualiza pequeño en el modo responsive, existe espacio para ampliar la vista del logo.
- [ ] La etiqueta de agotado cubre toda la imagen del producto e incluso en ocasiones el tapa el nombre del producto.
- [ ] Al abrir el menú donde se ven las categorías, sale el botón para abrir su categoría, pero si se presiona no hace nada, en el modo web ese icono no se visualiza.
- [x] Los datos de teléfono, dirección y correo deberían tener acciones, abrir google maps, whatsapp o para enviar un correo.
- [x] Incluir icono de TikTok en redes sociales.
- [ ] Redondeo erróneo de la aplicación del descuento en el cintillo de la ficha del producto

- [x] Desde la vercion web de la tienda online se muestran las imagenes cuando esta desde un movil,  ya no se muestran  

**Acceptance Test**
none

**Implementation Notes**
none

**Subtasks**
none

**Planning Estimate**
6

**References**
https://www.notion.so/Correcciones-para-la-tienda-online-8094d60d13d84f4cb88024cdf853b097
https://www.notion.so/Tickets-Desarrollo-4dd84eb09af7404aa194636d5d47868e?p=62eee01d9c02404cb80bb29b2e335255&pm=s
