### ISSUE TITLE
T:08/04 - Gracias por tu compra TE: 6 h

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#198]
**Overview**
Actividades para maquetación e integración de pantalla final al crear un pedido

**Issues**
- [x] 1.5h -#206 Maquetar e integrar sección de cabecera
- [x] 1.5 h - #212 Maquetar e integrar sección de resumen de productos solicitados en pedido
- [x] 1.5 h - #215 Maquetar e integrar sección de resumen de datos del pedido (método de pago, dirección de envío, datos de facturación, etc)
