### ISSUE TITLE
T: 07/4 Maquetación Componente Header

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebLandingEcommerce#2]
**Overview**
Maquetación Componente Header

**Issues**
- [x] Maquetar Header en desktop y responsive #21
- [x] Maquetar menu categorias #28
- [x] Maquetar Menú logueo #29
- [x] Maquetar menu categoria #31
- [x] Maquetar botones header #33
- [x] Maquetar buscador #36
- [x] Maquetar modal iniciar sesion #39 
- [x] Maquetar menu categorias mobile #54
