### ISSUE TITLE
T: 08/04 - Pantalla Perfil de Usuario - TE: 6 h

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#222]
**Overview**
Actividades pendientes para terminar pantalla ***Perfil de Usuario***

**Issues**
- [x] 1.5 h #229 Proteger ruta de perfil de usuario.
- [x] 2.5 h #239 Cargar imágenes de voucher en detalle de pedido.
- [x] 1 h - #225 Integrar servicio de favoritos
- [x] 1 h - #226 Funcionalidad para ***Cerrar sesión***
