### ISSUE TITLE
T:10/02 Pendientes MRC

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#293]
**Overview**
Actividades pendientes por avance en Ecommerce-Japisale

**Issues**
- [x] #294 0.5 h El buscador del Banner debe mostrarse de acuerdo a una variable de entorno
- [x] #300 0.5 h Integrar Información de la compañía para que se muestre debajo del banner
- [x] #311 1 h Banner de descuento dinámico.
- Enlaces desde el footer
- [x] #296 0.25 h Eliminar componente ***Boletín de suscripción***
- [x] #301 0.5 h Actualizar estilos en menú de categorías
- [x] #313 0.5 h Banner lateral en detalle de producto debe ser dinámico
- Definir productos debajo de banner lateral en detalle de producto
- 1.5 h Login con facebook
- [x] #309 1.5 h Mostrar datos del pedido al regresar de métodos de pago
- 1.5 h Cambiar diseño de correo
- [x] #303 0.5 h Componente de calificación no puede ser modificado por usuario
- [x] #305 0.5 h Bloquear botón de registro de usuario hasta aceptar **Términos y condiciones**
- Definir información a mostrar al presionar **Términos y condiciones**
