### ISSUE TITLE
T: 11/03 Actualización detalle de Producto

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#332]
**Overview**
Actividades requeridas para actualizar la pantalla de detalle de producto

**Issues**
- [x] #342 1.5 h Crear componente **Conversiones**.
- [x] #333 3 h Actualizar componente **Características**.
- [x] #351 3 h Funcionalidad para mostrar contenido por **Conversión** seleccionada.
