### ISSUE TITLE
T: [] - Mejoras en el Ecommerce.

### ISSUE THREAD

**Issue by QA-TONY** [apprunn/dp6WebLandingEcommerce#335]
**Overview**
Mejoras en el Ecommerce, correspondiente a la semana del 25-11 al 29-11.

**Issues**
* [x] - 1 h Modificar colores en iconos del Home #336  
* [x] - 0.5 h Modificar colores en icono de favorito #337
* [ ] - Culminar "Centro de Ayuda"
* [x] - 1 h Integrar banner en detalle de producto. #338
* [x] - 0.5 h Integrar nombre en perfil del cliente #339
* [x] - 0.75 h Integrar logos y enlaces de redes sociales. #341
* [ ] - 1.5 h Corregir información a guardar en el local storage. #348
