### ISSUE TITLE
T: 03/01 Informe de incidencias 2

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#435]
**Overview**
Actividades para corregir detalles levantados en los ecommerce

**Issues**
- [x] #444 validar DNI en formulario de responsable. No está funcionando la validación ya que con correo electrónico se habilita el botón de pago
- [x] Modifico validación para de error al ingresar con un token expirado 0.5h #446 
- [x] #448 Al hacer hover en la categoría debe aparecer el color secundario como background
- [x] #451 Se muestran tarjetas en footer si el comercio las tiene configuradas
- [x] Eliminar botón para calculo de envío en pantalla de método de pago #453 0.5h
- [x] En método de pago mantener un ancho fijo para que al cambiar de método de pago no hayan cambios 0.5h #455 
- [x] 2 h Reemplazar tab de estados por selector en mis pedidos #458 
- [x] Calificar un producto solo en el detalle del pedido y no en detalle de producto 1.5h #456 
- [x] 1.5 h #545 Agregar filtro "Ver todo" en home TBD
- [x] Error al cargar el avatar en el perfil de usuario TBD
- [x] En pantalla de pagos se muestra el header y footer en gris. Aparentemente un servicio no esta retornando (no sucede siempre)
- [x] Crear nueva variables para estados de orden (actualmente la variable orderStateId recibe esta información y el id de la orden en distintos flujos)
- [x] #459 Cambiar color del precio en tarjeta de producto.
- [x] #471 No se agregan los productos en el pedido al editarlo
- [x] #473 Cambiar palabra ***Categoría*** por ***Menú***
- [x] #475 El gris en detalle de producto debe ser más oscuro
- [x] #482 Ubigeo dinámico Peru-Ecuador
- [x] #477 Agregar las palabras ***Editar*** y ***Cambiar foto*** en perfil de usuario
- [x] #479 Producto con 3 decimales
- [x] #481 Agregar botones en pantalla final de carrito de compras
