### ISSUE TITLE
T 02/04: Pasarela de pago Ecuador. TE: 5h

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#486]
**Overview**
Implementar pasarela de pago para Ecuador

**Issues**
- [x] #487 Crear Objeto del método de pago al cargar la página.
- [x] #517 Mostrar botón de pago en pago con tarjeta de crédito.
- [x] #526 Integrar credenciales para pasarela de pago en entorno desarrollo
