### ISSUE TITLE
T 02/04: Mejoras en Ecommerce. TE: 20

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#498]
**Overview**
_**Required.** Detailed description of the functionality contained in this Topic._

**Issues**
- [x] #503 Cerrar menú de categorías haciendo click afuera del mismo
- [x] #505 Variable orderStatus muta con valores incorrectos
- [x] #501 Version móvil del carrusel en detalle de producto está roto.
- [x] #507 En campo `DNI` se muestra correo.
- [x] #499 Cambiar ícono de Carrito de compras por Canasta de compra.
- [x] Agregar modal para confirmar cancelación de pedido en perfil de usuario
- [x] #519 Diferenciar productos por conversiones en carrito de compras
- [x] #523 Agregar modal de confirmación al agregar producto al carrito de compra
- [x] #509 Enviar objeto `deliveryAddress` en todo momento.
- [x] #521 Enviar todos los datos de la dirección al editar pedido
- [x] #515 Agregar botón para regresar al ***Home*** desde el perfil de usuario
- [x] #513 Solicitar inicio de sesión después de la primera pantalla del carrito de compras
- [x] #524 Actualizar eliminación de productos del carrito de compras
