### ISSUE TITLE
T: 07/4 Maquetación Lista de Productos

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebLandingEcommerce#5]
**Overview**
Maquetación Lista de Productos

**Issues**
- [x] #14 Cuadro de descuento
- [x] #14 Botón para marcar como favorito
- [x] #14 Imagen de producto
- [x] #14 Información de producto
- [x] #14 Rating
- [x] #14 Card de producto
- [x] #14 Lista de productos
