### ISSUE TITLE
T 03/02: Mejoras Ecommerce

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#528]
**Overview**
Ecuador propone una serie de mejoras para el ecommerce

**Issues**
- [x] #530 - 1h Eliminar validación de documento de identidad para responsable (Solo Ecuador)
- [x] #532 - 2h. Implementar meta dinámicos en el Ecommerce
- [x] #529 - 0.5h Mostrar error de correo existente al registrase
- [x] #539 0.5 h Crear archivo countries.json para variables de paises
