### ISSUE TITLE
T02/05: Integrar DATAFAST. TE: 8.5 h

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#581]
**Overview**

**Issues**
- [x] 1 h Crear Nuevo componente para ***DataFast***. #582 
- [x] 3 h Mostrar formulario de pago. #584
- [x] 3 h Realizar prueba de pago en desarrollo. #586 
- [x] 1.5 Modal para formulario de data fast #587
