### ISSUE TITLE
T02/05: Implementar nuevo centro de ayuda

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#591]
**Overview**
Se requiere mostrar el centro de ayuda configurado por el usuario en el administrador

**Issues**
- [x] 1.5 h Maquetar estructura base de pantalla #592 
- [x] 1.5 h Integrar servicio para mostrar información. #595
- [x] 2 h Al recargar página se pierde la información. #597
- [x] 2 h Centro de ayuda versión móvil #601
