### ISSUE TITLE
T03/05: Integración Yape. TE: 5.5 h

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#598]
**Overview**
Actividades requeridas para integrar el sistema de pagos ***Yape***

**Issues**
- [x] 2 h Realizar diagrama de flujo del sistema de pago ***Yape***
- [x] 2 h Mostrar botón ***Yape*** en sección de métodos de pago. #606 
- [x] 1 h Mostrar modal con código QR de ***Yape*** #609
- [x] 0.5 h Mostrar imagen que viene en servicio para Yape. #611
- [x] 0.5 h Mostrar modal de confirmación de pago con ***Yape*** #613
