### ISSUE TITLE
I[3](PHP): Extraer html, css y js solo del perfil de usuario

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#637]
**Topic**
N/A

**Description**
Se requiere todo el `html, `css` y `js` del perfil de usuario. Para ello se hará de la siguiente manera:
- Layout principal = corresponde a la pantalla de ***Mis datos personales***
- Porciones o chunks posteriores de solo html = ***Mis Órdenes***, ***Mis Direcciones***, ***Mis Favoritos***
- El Layout principal debe tener todos los `css` y `js` necesarios para el ***Perfil de Usuario***

**Acceptance Test**
- Cuatro archivos separados
- El archivo principal contiene todo el `js` y `css` necesario
- Los archivos secundarios solo el `html` con las clases

**Implementation Notes**
none

**Subtasks**
N/A

**Planning Estimate**
3 h

**References**
none

**Latest Assets**
N/A

**Comment by JoseJuan81** [comment]
## Archivos relacionados al perfil de usuario
- [x] App.vue
   - [x] getters.js
   - [x] lib.js
   - [x] app-banner-top.vue
   - [x] app-header.vue
      - [x] call-menu.vue
   - [x] app-menu-category.vue
      - [x] app-banner-plan.vue
      - [x] app-category.vue
      - [x] app-customer-discount.vue
      - [x] call-menu.vue
      - [x] item-menu.vue
      - [x] modal-login.vue
   - [x] app-footer.vue
      - [x] section-links.vue
      - [x] section-visa
   - [x] Layout-admin.vue
   - [x] Page-Profile.vue   
      - [x] Left-component.vue
      - [x] user-data.vue
      - [x] edit-component.vue
      - [x] UploadImage.vue
         - [x] user-data-details.vue
         - [x] edit-user-data.vue
            - [x] app-input.vue
            - [x] app-select.vue
            - [x] app-button.vue
      - [x] user-orders.vue
         - [x] profile-tab.vue
         - [x] responsive-table.vue
         - [x] details-component.vue
         - [x] delete-component.vue
         - [x] modal-component.vue
      - [x] favorites
         - [x] responsive-table.vue
         - [x] car-component.vue
         - [x] delete-component.vue
      - [x] address-data.vue
         - [x] new-address-form.vue
         - [x] responsive-table.vue
         - [x] star-component.vue
         - [x] delete-component.vue

**Comment by JoseJuan81** [comment]
No es posible usar este método ya que el comando `npm run build` no crea el archivo html por completo. En su lugar crea un "Layout" y con archivos javascript va actualizando el DOM
