### ISSUE TITLE
T04/06: Implementar pasarela de pago XCHANGE

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#680]
**Overview**
Actividade requeridas para implementar pasarela de pago ***Xchange***

**Issues**
- [x] #682  0.5 h Crear archivo nuevo para pasarela de pagos ***Xchange***
- [x] #681 1.5 h Mostar botón de pago en pantalla de pagos del ecommerce.
- [x] #685 2 h Presionar botón de pago y mostrar formulario.
- [x] #687 2 h Integrar formulario con datos del usuario y comercio
- [x] #689 2 h Realizar pruebas en desarrollo de la pasarela 
- [x] #690 2 h Integrar pasarela de pagos con datos del comercio
