### ISSUE TITLE
T02/08: Nueva pantalla de resumen de pedido

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#769]
**Overview**
Issues requeridos para crear nueva pantalla de resumen de pedido

**Issues**
- [x] #770 Maquetar layout de la pantalla
- [x] #774 Maquetar componente **Producto**
- [x] #776 Maquetar componente dinámico para medios de pagos y costo de envío
- [x] #784 Implementar botones de ***Cancelar*** y ***Ver Pedido***

No other links are allowed._
