### ISSUE TITLE
T: 07/4 Login, registro y olvidaste tu contraseña TE: 3h

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebLandingEcommerce#8]
**Overview**
Login, registro y olvidaste tu contraseña

**Issues**
- [x] Input y labels con estilos para formularios #15 
- [x] Botones con estilos para formularios #16 
- [x] Formulario para ingresar datos de registro #18 
- [x] Formulario para ingresar datos de inicio de sesión #17 
- [x] Inicio de sesión con facebook #19 
- [x] 3h : Formulario para restaurar contraseña #20
