### ISSUE TITLE
T: Mejoras al integrar informacion con datafast en el commerce 4.95h

### ISSUE THREAD

**Issue by airomerick98** [apprunn/dp6WebLandingEcommerce#859]
**Overview**
Mejoras al integrar informacion con datafast
**Issues**
- [x] Mostrar botón de "datafast" si existem uno o mas tarjetas de pago #860
- [x]  Corregir botón "datafast" , agregarle border según el comercio. #861
- [x] Mostrar el nombre y la imagen segun el medio de tarjetas. #862
- [x] Corregir estilos de selectores al abrir el modal de ingresar tarjeta #863
- [x]  Agregar nuevos items en el selectores de deferidos 0 , 3 , 6 y 12 #864
- [x]  Validar botón de datafast al abrir el modal #875
