### ISSUE TITLE
T: 07/4 Perfil de usuario

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebLandingEcommerce#9]
**Overview**
Perfil de usuario

**Issues**
- [x] #25 Maquetar estructura de pantalla de perfil de usuario para versión web y  móvil.
- [x] #27 Menú de perfil de usuario
- [x] #34 Sección datos personales (mostrar / editar)
- [x] #46 Sección mis órdenes => Tabs
- [x] #49 Sección mis órdenes (listado)
- [x] #52 Componente de selección
- [x] #58 Sección mis órdenes (detalle)
- [x] #67 Sección mis órdenes (favoritos)
