### ISSUE TITLE
T03/10: Observaciones Trello - TE: 12.5 h

### ISSUE THREAD

**Issue by JoseJuan81** [apprunn/dp6WebLandingEcommerce#910]
**Overview**
Listado de actividades levantadas en ***Trello***

**Issues**
- [x] 1 h  GENERAL - No se muestran las subcategorias.
https://trello.com/c/mhGBkmBe/42-general-no-se-muestran-las-subcategorias
- [ ] 6 h 1. DIARCA-METADATOS
https://trello.com/c/RwATgFVT/2-1-diarca-metadatos
- [ ] 3 h 20. SOLINTHA-CAMBIO DE TEMPLATE A MI STORE (implementar carrito de shoppyrunn con paymentez)
https://trello.com/c/7lcwkdPq/13-20-solintha-cambio-de-template-a-mi-store
- [x] 1.5 h  35. AUTOPARTES VIN- PROBLEMAS EN STOK
https://trello.com/c/ls4SdBm8/16-35-autopartes-vin-problemas-en-stok
- [x] 1 h 1029. Error al aparecer el -0% si no se apuesto ningún descuento
https://trello.com/c/9cCfAeUE/41-1029-error-al-aparecer-el-0-si-no-se-apuesto-ning%C3%BAn-descuento
- [x] #914 Eliminar **Quitar +1000 compraron.** en tarjeta de productos
- [x] #914 Aumentar el tamaño del precio tachado cuando tiene descuento en tarjeta de producto (14px)
- [x] #914 Agregar descripción del producto en la tarjeta de producto
