### ISSUE TITLE
T: 11/1 2.8h - Bugs Ecommerce

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebLandingEcommerce#945]
**Overview**
Bugs Ecommerce

**Issues**
- [x] Mostrar último paso de compra en versión responsive 1h #946 
- [x] Cambio de estilos en listado de pedidos 0.8h #948 
- [x] Verificar información de banco en formulario de pago 0.5h #949 
- [x] Agregar el campo `Dpto - Ofic.` en el formulario de dirección 0.5h #950
